### ISSUE TITLE
Incluir na badge do CircleCI no Readme o link que leva pra última execução

### ISSUE THREAD

**Issue by samycici** [felipsimoes/MagnetonTests#2]

**Comment by felipsimoes** [comment]
Parcialmente resolvido no commit ccf9e157f63ea6919f473bfacb70fa131f83a4ac
Procurei na doc mas não encontrei referência a algum link público para o último build, algo como https://circleci.com/gh/felipsimoes/MagnetonTests/latest todos os builds são referenciados pelo número da execução
